### ISSUE TITLE
Replace @types/rdf-js with @rdfjs/types

### ISSUE THREAD

**Issue by jeswr** [soltanireza65/data-modules-monorepo#1]
Usage of `@types/rdf-js` should be `@rdfjs/types` instead. See https://github.com/rdfjs/types?tab=readme-ov-file#what-about-typesrdf-js

This was discovered in the search https://github.com/search?q=%22%5C%22%40types%2Frdf-js%5C%22%3A+%5C%22%22+language%3AJSON+NOT+is%3Afork+path%3A**%2Fpackage.json&type=code

**Comment by soltanireza65** [comment]
I'm going to remove this repo, since now we have `https://github.com/solid-contrib/data-modules`
[sea](https://github.com/solid-contrib/data-modules/blob/478f62c4af4ca055c3a2cbae3087827159585230/bookmarks/vanilla/src/modules/Bookmark.ts#L28C1-L29C1)
and it should actively be developing. I'm not sure btw
